import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalState } from "./context/GlobalState";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DBMS project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  axios.defaults.withCredentials = true;
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>{children}</GlobalState>
      </body>
    </html>
  );
}
